<?php
/**
 * Magento
 *
 * @category   Idpay
 * @package    Idpay_Idpay
 */
?>

<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <img src="<?php echo $this->getPaymentImageSrc(); ?>" alt="<?php echo $this->getMethod()->getTitle() ?>" width="90px"/>
        <li>
            <?php echo $this->__('You will be redirected to Idpay website when you place an order.') ?><br />
        </li>
    </ul>
</fieldset>